# Python basic stuff

## Variables and Jupyter demo

In [8]:
2+4+5

11

In [2]:
a = 55

In [3]:
type(a)

int

In [4]:
b = 77.
b

77.0

In [5]:
type(b)

float

In [6]:
b

77.0

In [ ]:
c

## Jupyter markdown stuff

Text is Ok with Markdown. Math is also with $\LaTeX$.

Youn can create inline math $\alpha = 5$ :

$$
A = \int_0^{+\infty} f(x) dx
$$



## Pure Python for science

In [10]:
from math import sin

def my_func(x):
    return sin(x) + x**2 + 5 

In [12]:
my_func(3)

14.141120008059866

In [15]:
x_values = [1, 2, 3, 4] # CREATING A LIST : LONG AND PAINFUL
x_values

[1, 2, 3, 4]

In [16]:
my_func(x_values)

TypeError: must be real number, not list

In [18]:
y_values = []
for xv in x_values:
    y = my_func(xv)
    y_values.append(y)
y_values

[6.841470984807897, 9.909297426825681, 14.141120008059866, 20.24319750469207]

### Use of Numpy

In [19]:
import numpy as np

In [23]:
def my_func2(x):
    return np.sin(x) + x**2 + 5 

In [24]:
x_array = np.array(x_values)
x_array

array([1, 2, 3, 4])

In [25]:
my_func2(x_array)

array([ 6.84147098,  9.90929743, 14.14112001, 20.2431975 ])

## Deeper in Numpy

In [28]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
b = np.linspace(0., 1., 11)
b

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [30]:
b**2

array([0.  , 0.01, 0.04, 0.09, 0.16, 0.25, 0.36, 0.49, 0.64, 0.81, 1.  ])

In [31]:
2**a

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])

In [32]:
c = np.arange(36) 
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [34]:
d = c.reshape(6,6)
d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [35]:
d.shape

(6, 6)

In [37]:
d[0] # INDEXING

array([0, 1, 2, 3, 4, 5])

In [39]:
d[0:4] # SLICING

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [42]:
d[:4]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [44]:
d[:, 4]

array([ 4, 10, 16, 22, 28, 34])

In [46]:
(d > 4) & (d <25)

array([[False, False, False, False, False,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [47]:
d[(d > 4) & (d <25)]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

## Plotting with Matplotlib

In [55]:
%matplotlib widget
import matplotlib.pyplot as plt

In [56]:
x = np.linspace(0., 10., 100) # X VALUES
y = my_func2(x)

In [ ]:
fig = plt.figure()
plt.plot(x, y)
plt.grid() 
plt.xlabel("Time, $x$")
plt.ylabel("Signal amplitude, $y$")
plt.title("Awesome data")
plt.show()


In [67]:
plt.savefig("my_fig.png") # CAN ALSO BE PDF FOR VECTOR GRAPHICS

A file was created:

![](my_fig.png)